---
- name: "CONFIGURING LOOPBACK WITH CISCO IOS MODULES"
  hosts: ios
  connection: ansible.netcommon.network_cli


  tasks:


    - name: "CREATE LOOPBACK 1"
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback1


    - name: "IP ADDRESS Lo1 ON R1"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.1/32
      when: inventory_hostname == 'IOS1'

    - name: "IP ADDRESS Lo1 ON R2"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.2/32
      when: inventory_hostname == 'IOS2'

    - name: "IP ADDRESS Lo1 ON R3"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.3/32
      when: inventory_hostname == 'IOS3'

    - name: "IP ADDRESS Lo1 ON R4"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.4/32
      when: inventory_hostname == 'IOS4'

#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result.commands }}"
