---
- name: "CONFIGURING IOS ROUTER"
  hosts: ios
  connection: ansible.netcommon.network_cli


  tasks:


    - name: "CREATE LOOPBACK 101, 102, 103, 104"
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback101
          - name: Loopback102
          - name: Loopback103
          - name: Loopback104


    - name: "IP ADDRESS 101, 102, 103, 104"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback101
            ipv4:
              - address: 10.10.101.1/32
          - name: Loopback102
            ipv4:
              - address: 10.10.102.1/32
          - name: Loopback103
            ipv4:
              - address: 10.10.103.1/32
          - name: Loopback104
            ipv4:
              - address: 10.1.104.1/24
      register: cli_result_task1


    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 64496
#          as_number: 45000
          bgp:
            router_id:
              address: 192.0.2.1
            log_neighbor_changes: true
          neighbors:
            - address: 203.0.113.5
              remote_as: 64511
              route_map:
                name: RMAP_1
                out: true
        state: merged
      register: cli_result_task3


    - name: "CREATE STATIC ROUTEs"
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 99.99.99.99/32
                    next_hops:
                      - forward_router_address: null0
                        name: ANSIBLE-ROUTE
      register: cli_result_task4


#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result_task1.commands }}"

#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result_task3.commands }}"

#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result_task4.commands }}"
