---
- name: "GET FACTS"
  hosts: datacenter


  tasks:

    - name: Gather minimal legacy facts
      cisco.ios.ios_facts:
        gather_subset: min
      register: output

#    - name: Show collected facts
#      ansible.builtin.debug:
#        var: output

    - name: Show IOS version
      ansible.builtin.debug:
        var: output.ansible_facts.ansible_net_version
