---
- name: "CONFIGURING IOS ROUTER"
  hosts: ios
  connection: ansible.netcommon.network_cli


  tasks:


    - name: "CREATE LOOPBACK 101 ON IOS1"
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback101


    - name: "IP ADDRESS 101 ON R1"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback101
            ipv4:
              - address: 10.10.101.1/32
      when: inventory_hostname == 'IOS1'

    - name: "IP ADDRESS 101 ON R2"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback101
            ipv4:
              - address: 10.10.102.1/32
      when: inventory_hostname == 'IOS2'

    - name: "IP ADDRESS 101 ON R3"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback101
            ipv4:
              - address: 10.10.103.1/32
      when: inventory_hostname == 'IOS3'


    - name: "CREATE STATIC ROUTEs"
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 99.99.99.99/32
                    next_hops:
                      - forward_router_address: null0
                        name: ANSIBLE-ROUTE
      register: cli_result


#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result.commands }}"
