---
- name: "CONFIGURING LOOPBACK WITH CISCO IOS MODULES"
  hosts: dc
  gather_facts: false


  tasks:


    - name: "CREATE LOOPBACK 1"
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback1


    - name: "IP ADDRESS Lo1 ON R1"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.1/32
      when: inventory_hostname == 'DC1-R1'

    - name: "IP ADDRESS Lo1 ON R2"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.2/32
      when: inventory_hostname == 'DC1-R2'

    - name: "IP ADDRESS Lo1 ON R3"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.3/32
      when: inventory_hostname == 'DC2-R1'

    - name: "IP ADDRESS Lo1 ON R4"
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback1
            ipv4:
              - address: 1.1.1.4/32
      when: inventory_hostname == 'DC2-R2'
