---
- name: "CONFIGURING INTERFACES WITH NETCOMMON MODULE"
  hosts: dc


  tasks:


    - name: "Configuring Interfaces"
      ansible.netcommon.cli_config:
        config: |
          interface GigabitEthernet0/1
           ip address 192.168.12.0 255.255.255.254
           no shutdown
          interface GigabitEthernet0/2
           ip address 192.168.13.0 255.255.255.254
           no shutdown
      when: inventory_hostname == 'DC1-R1'

    - name: "Configuring Interfaces"
      ansible.netcommon.cli_config:
        config: |
          interface GigabitEthernet0/1
           ip address 192.168.12.1 255.255.255.254
           no shutdown
          interface GigabitEthernet0/2
           ip address 192.168.24.0 255.255.255.254
           no shutdown
      when: inventory_hostname == 'DC1-R2'

    - name: "Configuring Interfaces"
      ansible.netcommon.cli_config:
        config: |
          interface GigabitEthernet0/1
           ip address 192.168.34.0 255.255.255.254
           no shutdown
          interface GigabitEthernet0/2
           ip address 192.168.13.1 255.255.255.254
           no shutdown
      when: inventory_hostname == 'DC2-R1'

    - name: "Configuring Interfaces"
      ansible.netcommon.cli_config:
        config: |
          interface GigabitEthernet0/1
           ip address 192.168.34.1 255.255.255.254
           no shutdown
          interface GigabitEthernet0/2
           ip address 192.168.24.1 255.255.255.254
           no shutdown
      when: inventory_hostname == 'DC2-R2'

#    - name: "Show Interfaces"
#      ansible.netcommon.cli_command:
#        command: show ip interface brief
#      register: cli_result
#
#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result }}"
#        # msg: "{{ cli_result.stdout_lines }}"
