---
- name: "CONFIGURING ROUER BGP"
  hosts: ios
  connection: ansible.netcommon.network_cli
  vars_files:
    - bgp_vars.yml

  tasks:

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: "{{ item.as_number }}"
#          as_number: 45000
          bgp:
            router_id:
              address: "{{ item.router_id }}"
            log_neighbor_changes: true
          neighbors:
            - address: "{{ item.neighbor }}"
              remote_as: "{{ item.remote_as }}"
              route_map:
                name: "{{ item.route_map_out }}"
                out: true
        state: merged
      when: inventory_hostname == item.router_target
      loop: "{{ router_bgp }}"
      register: cli_result


#    - name: "OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ cli_result.commands }}"
