---
- name: "CONFIGURING BGP WITH ANSIBLE ROLE"
  hosts: dc


  tasks:

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.1
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.12.1
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC1-R1"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.1
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.13.1
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC1-R1"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.2
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.12.0
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC1-R2"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.2
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.24.1
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC1-R2"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.3
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.13.0
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC2-R1"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.3
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.34.1
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC2-R1"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.4
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.24.0
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC2-R2"

    - name: "CONFIGURE ROUTER BGP"
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            router_id:
              address: 1.1.1.4
            log_neighbor_changes: true
          neighbors:
            - neighbor_address: 192.168.34.0
              remote_as: 65001
              soft_reconfiguration: true
              send_community:
                both: true
              next_hop_self:
                set: true
          redistribute:
            - connected:
                set: true
        state: merged
      when: inventory_hostname == "DC2-R2"
