---
- name: "PLAY 2: CONFIGURATION ACI FABRIC"
  hosts: apic
  connection: local
  gather_facts: false
  vars:
    # yaml macro
    apic_info: &apic_info
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false
  vars_files:
    - aci_vars.yml

  tasks:

    - name: "CREATE TENANT"
      cisco.aci.aci_tenant:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        description: "{{ tenant.tenant_desc }}"


    - name: "CREATE VRF"
      cisco.aci.aci_vrf:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        vrf: "{{ vrf.vrf_name }}"


    - name: "CREATE BRIDGE DOMAIN"
      cisco.aci.aci_bd:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        vrf: "{{ vrf.vrf_name }}"
        bd: "{{ bd.bd_name }}"
        enable_routing: "{{ bd.bd_unicast }}"


    - name: "CREATE APPLICATION PROFILE"
      cisco.aci.aci_ap:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        ap: "{{ ap.ap_name }}"


    - name: "CREATE EPGs"
      cisco.aci.aci_epg:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        ap: "{{ ap.ap_name }}"
        bd: "{{ bd.bd_name }}"
        epg: "{{ item }}"
      with_items: "{{ epg.epg_name }}"


    - name: "CREATE WEB-TO-APP CONTRACT"
      cisco.aci.aci_contract:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        contract: web_to_app_ct


    - name: "CREATE WEB-TO-APP SUBJECT"
      cisco.aci.aci_contract_subject:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        contract: web_to_app_ct
        subject: SBJ
        reverse_filter: true


    - name: "BIND WEB-TO-APP SBJ + FILT"
      cisco.aci.aci_contract_subject_to_filter:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        contract: web_to_app_ct
        subject: SBJ
        filter: web_to_app_filt


    - name: "CREATE WEB-TO-APP FILTER"
      cisco.aci.aci_filter:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        filter: web_to_app_filt


    - name: "CREATE WEB-TO-APP FILTER ENTRY"
      cisco.aci.aci_filter_entry:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        filter: web_to_app_filt
        entry: tomcat
        ether_type: ip
        ip_protocol: tcp
        dst_port: "9090"


    - name: "CREATE APP-TO-DB CONTRACT"
      cisco.aci.aci_contract:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        contract: app_to_db_ct


    - name: "CREATE APP-TO-DB SUBJECT"
      cisco.aci.aci_contract_subject:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        contract: app_to_db_ct
        subject: SBJ
        reverse_filter: true


    - name: "BIND APP-TO-DB SBJ + FILT"
      cisco.aci.aci_contract_subject_to_filter:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        contract: app_to_db_ct
        subject: SBJ
        filter: app_to_db_filt


    - name: "CREATE APP-TO-DB FILTER"
      cisco.aci.aci_filter:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        filter: app_to_db_filt


    - name: "CREATE APP-TO-DB FILTER ENTRY"
      cisco.aci.aci_filter_entry:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        filter: app_to_db_filt
        entry: mysql
        ether_type: ip
        ip_protocol: tcp
        dst_port: "3306"


    - name: "INSTALL WEB CONSUMER CONTRACT"
      cisco.aci.aci_epg_to_contract:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        ap: "{{ ap.ap_name }}"
        epg: web
        contract: web_to_app_ct
        contract_type: consumer


    - name: "ISNTALL APP PROVIDER CONTRACT"
      cisco.aci.aci_epg_to_contract:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        ap: "{{ ap.ap_name }}"
        epg: app
        contract: web_to_app_ct
        contract_type: provider


    - name: "INSTALL APP CONSUMER CONTRACT"
      cisco.aci.aci_epg_to_contract:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        ap: "{{ ap.ap_name }}"
        epg: app
        contract: app_to_db_ct
        contract_type: consumer


    - name: "INSTALL DB PROVIDER CONTRACT"
      cisco.aci.aci_epg_to_contract:
        <<: *apic_info
        tenant: "{{ tenant.tenant_name }}"
        ap: "{{ ap.ap_name }}"
        epg: db
        contract: app_to_db_ct
        contract_type: provider
