---
# vars file for bgp-ios-demo
router_bgp:
  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.12.1
    remote_as: 65001
    soft: true
    router_target: IOS1
  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.12.0
    remote_as: 65001
    soft: true
    router_target: IOS2

  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.34.1
    remote_as: 65001
    soft: true
    router_target: IOS3
  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.34.0
    remote_as: 65001
    soft: true
    router_target: IOS4

  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.13.1
    remote_as: 65001
    soft: true
    router_target: IOS1
  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.13.0
    remote_as: 65001
    soft: true
    router_target: IOS3

  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.24.1
    remote_as: 65001
    soft: true
    router_target: IOS2
  - as_number: 65001
    router_id: "{{ RID }}"
    neighbor: 192.168.24.0
    remote_as: 65001
    soft: true
    router_target: IOS4
