---
- name: "PLAY 1: CONFIGURING NEXUS SWITCH"
  hosts: nexus_sandbox
#  hosts: nexus_esx
  connection: network_cli
  tasks:

    - name: "TASK 1: CREATE LOOPBACK 101, 102, 103, 104"
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: loopback 101
            ipv4:
              - address: 10.10.101.1/32
          - name: loopback 102
            ipv4:
              - address: 10.10.102.1/32
          - name: loopback 103
            ipv4:
              - address: 10.10.103.1/32
          - name: loopback 104
            ipv4:
              - address: 10.10.104.1/32


      register: cli_result_task1

#    - name: "TASK 1b: OUTPUT"
#      debug:
#        msg: "{{ cli_result_task1.commands }}"


    - name: "TASK 2: CREATE ACLs"
      cisco.nxos.nxos_acls:
        config:
        - afi: ipv4
          acls:
            - name: ANSIBLE-ACL
              aces:
                - grant: permit
                  source:
                    any: true
                  destination:
                    address: 1.1.1.1
                    wildcard_bits: 0.0.0.0
                    port_protocol:
                      eq: "443"
                  protocol: tcp
                - grant: permit
                  source:
                    any: true
                  destination:
                    address: 2.2.2.2
                    wildcard_bits: 0.0.0.0
                    port_protocol:
                      eq: "443"
                  protocol: tcp
                - grant: permit
                  source:
                    any: true
                  destination:
                    address: 3.3.3.3
                    wildcard_bits: 0.0.0.0
                    port_protocol:
                      eq: "443"
                  protocol: tcp

      register: cli_result_task2

#    - name: "TASK 2b: OUTPUT"
#      debug:
#        msg: "{{ cli_result_task2.commands }}"




    - name: "TASK 3 CREATE ROUTE-MAP"
      cisco.nxos.nxos_config:
        lines:
        - "match ip address ANSIBLE-ACL"
        - "set local-preference 150"
        parents: route-map ANSIBLE-MAP permit 10

      register: cli_result_task3

#    - name: "TASK 3b: OUTPUT"
#      debug:
#        msg: "{{ cli_result_task3 }}"



    - name: "TASK 4: CREATE STATIC ROUTEs"
      cisco.nxos.nxos_static_routes:
        config:
          - address_families:
            - afi: ipv4
              routes:
                - dest: 99.99.99.99/32
                  next_hops:
                  - forward_router_address: null0
                    route_name: ANSIBLE-ROUTE
        state: merged

      register: cli_result_task4

#    - name: "TASK 4b: OUTPUT"
#      debug:
#        msg: "{{ cli_result_task4.commands }}"


    - name: "TASK 5: OUTPUT"
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ cli_result_task1.commands }}"
        - "{{ cli_result_task2.commands }}"
        - "{{ cli_result_task3 }}"
        - "{{ cli_result_task4.commands }}"