---
- name: "PLAY 3: CONFIGURING NEXUS SWITCH"
#  hosts: nexus_sandbox
  hosts: nexus_esx
  connection: network_cli
  tasks:


######################################## TASK ##############################################àà

    - name: "TASK 1: SHUTDOWN Lo101"
      cisco.nxos.nxos_config:
        lines:
        - "interface loopback 101"
        - "shutdown"
      register: cli_result_task1

    - name: "TASK 2: SHUTDOWN Lo102"
      cisco.nxos.nxos_config:
        lines:
        - "interface loopback 102"
        - "shutdown"
      register: cli_result_task2

    - name: "TASK 3: SHUTDOWN Lo103"
      cisco.nxos.nxos_config:
        lines:
        - "interface loopback 103"
        - "shutdown"
      register: cli_result_task3



    - name: "TASK 4: OUTPUT"
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ cli_result_task1.changed }}"
        - "{{ cli_result_task2.changed }}"
        - "{{ cli_result_task3.changed }}"
