---
- name: "PLAY 3: CONFIGURING CSR ROUTER"
  hosts: csrv_esx
  connection: network_cli
  tasks:


######################################## TASK ##############################################àà

    - name: "TASK 1: SHUTDOWN Lo101"
      cisco.ios.ios_config:
        lines:
        - "interface Loopback 101"
        - "shutdown"


      register: cli_result

    - name: "TASK 1b: OUTPUT"
      debug:
        msg: "{{ cli_result.commands }}"
