---
- name: CONFIGURING CSR1000v
  hosts: test


  tasks:

    - name: Load variables
      ansible.builtin.include_vars:
        file: data.yaml
        name: router_configuration
      tags:
        - interface
        - vrf
        - sub-interface
        - ospf

    - name: Enable interface
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet2
            enabled: true
          - name: GigabitEthernet3
            enabled: true
      tags:
        - interface

    - name: Create sub-interface
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            enabled: true
      loop: "{{ router_configuration[inventory_hostname].subinterfaces }}"
      loop_control:
        label: "Created: {{ item.name }}"
      tags:
        - interface

    - name: Configure a vrf
      cisco.ios.ios_vrf:
        name: "{{ router_configuration.VRF.name }}"
        description: "{{ router_configuration.VRF.description }}"
      tags:
        - vrf

    - name: Add address-family ipv4 to VRF
      cisco.ios.ios_config:
        lines:
          - address-family ipv4 unicast
        parents:
          - vrf definition {{ router_configuration.VRF.name }}
      tags:
        - vrf

    - name: Configure sub-interface settings
      cisco.ios.ios_config:
        lines:
          - encapsulation dot1q {{ item.encap }}
          - vrf forwarding {{ router_configuration.VRF.name }}
          - ip address {{ item.address }} {{ item.mask }}
          - ip ospf network point-to-point
        parents: interface {{ item.name }}
      loop: "{{ router_configuration[inventory_hostname].subinterfaces }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - sub-interface

    - name: OSPF V2 configuration
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: "{{ item.process_id }}"
              router_id: "{{ item.router_id }}"
              vrf: "{{ router_configuration.VRF.name }}"
              network:
                - address: "{{ item.address }}"
                  wildcard_bits: "{{ item.wildcard_bits }}"
                  area: "{{ item.area }}"
      loop: "{{ router_configuration[inventory_hostname].OSPF }}"
      tags:
        - ospf
